In [1]:
! pip install numpy

In [2]:
import numpy as np

x = np.array([1,2,3,5])
print(x)
print(type(x))
x

[1 2 3 5]
<class 'numpy.ndarray'>


array([1, 2, 3, 5])

### 1-dimensional Numpy Array

In [7]:
x = np.arange(1,6)
print(x.ndim)
print(x)

1
[1 2 3 4 5]


### 2-dimensional Numpy Array

In [10]:
x = np.array([[234,321,53],[2342,53,2523]])
print(x.ndim)
print(x)

2
[[ 234  321   53]
 [2342   53 2523]]


### 3-dimensional NumpyArray

In [10]:
x = np.array([
    [
        [1,2],[4,5],[7,8]
    ],
    [
        [10,11],[13,14],[16,17]
    ],
    [
        [19,20],[22,23],[25,26]
    ]
    ])

print(x.ndim)
print(x)

3
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]


### Higher-order Dimensional Array

In [4]:
x = np.array([1,4,5],ndmin=5)
print(x.ndim)
print(x)

5
[[[[[1 4 5]]]]]


# Shape

In [2]:
import numpy as np
x = np.array([[234,321,53],[2342,53,2523]])
print(x)
print(x.ndim) # prints dimension of numpy array
print(x.shape) # prints shape(row,col) of numpy array

[[ 234  321   53]
 [2342   53 2523]]
2
(2, 3)


In [3]:
x = np.array([
    [
        [1,2],[4,5],[7,8]
    ],
    [
        [10,11],[13,14],[16,17]
    ],
    [
        [19,20],[22,23],[25,26]
    ]
    ])

print(x)
print(x.ndim)
print(x.shape)

[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
3
(3, 3, 2)


In [4]:
x = np.array([1,2,3,5,7], ndmin=7)
print(x)
print(x.ndim)
print(x.shape)

[[[[[[[1 2 3 5 7]]]]]]]
7
(1, 1, 1, 1, 1, 1, 5)


# Re-shape

### Changing dimensions of numpy array

In [20]:
arr = np.array([1,2,3,4,5,6])

reshape1 = arr.reshape(3,2)
print(reshape1)
print(reshape1.ndim)
print()
reshape2 = arr.reshape(6,1)
print(reshape2)
print(reshape2.ndim)
print()
reshape3 = arr.reshape(1,6)
print(reshape3)
print(reshape3.ndim)

[[1 2]
 [3 4]
 [5 6]]
2

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
2

[[1 2 3 4 5 6]]
2


In [22]:
arr = np.array([[1,2,6],[3,4,5]])
print(arr)
print(arr.ndim)
print(arr.shape)
print()
reshape1 = arr.reshape(3,2)
print(reshape1)
print(reshape1.ndim)
print()
reshape2 = arr.reshape(1,6)
print(reshape2)
print(reshape2.ndim)

[[1 2 6]
 [3 4 5]]
2
(2, 3)

[[1 2]
 [6 3]
 [4 5]]
2

[[1 2 6 3 4 5]]
2


#### Error-> If numpy array re-shaping requires more element than original array

In [19]:
arr = np.array([[1,2,6],[3,4,5]])
print(arr)

reshape = np.reshape(2,4)
print(reshape)

[[1 2 6]
 [3 4 5]]


ValueError: cannot reshape array of size 1 into shape (4,)

In [29]:
arr = np.array([1,2,6,3,4,5])
reshape = arr.reshape(3,2,1)
print(reshape)
print(reshape.ndim)

[[[1]
  [2]]

 [[6]
  [3]]

 [[4]
  [5]]]
3


### Converting to one dimension array from any

In [36]:
arr = np.array([[[1,2],[6,3],[4,5]],[[1,2],[3,4],[8,2]]])

print(arr)
print()
print(arr.ndim)
print()

reshape = arr.reshape(-1) # convert directly to one dimension array
print(reshape)
print(reshape.ndim)

[[[1 2]
  [6 3]
  [4 5]]

 [[1 2]
  [3 4]
  [8 2]]]

3

[1 2 6 3 4 5 1 2 3 4 8 2]
1
