In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
%pip install nptyping beartype


  Obtaining dependency information for beartype from https://files.pythonhosted.org/packages/46/8a/a90fe78c73958340ed6b6ab128a10598ad5f0ff57537ad17f6ccd1ad830b/beartype-0.16.4-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/819.1 kB ? eta -:--:--
   -- ------------------------------------- 41.0/819.1 kB 1.9 MB/s eta 0:00:01
   ---- ----------------------------------- 92.2/819.1 kB 1.3 MB/s eta 0:00:01
   -------- ------------------------------- 163.8/819.1 kB 1.2 MB/s eta 0:00:01
   ----------- ---------------------------- 225.3/819.1 kB 1.3 MB/s eta 0:00:01
   -------------- ------------------------- 286.7/819.1 kB 1.3 MB/s eta 0:00:01
   ---------------- ----------------------- 337.9/819.1 kB 1.2 MB/s eta 0:00:01
   -------------------- ------------------- 409.6/819.1 kB 1.2 MB/s eta 0:00:01
   ----------------------- ---------------- 471.0/819.1 kB 1.3 MB/s eta 0:00:01
   ------------------------- -------------- 522.2/819.1 kB 1.2 MB/s eta 0:00:01
   -----

## Scaler Value (Single-Dimensional)

In [9]:
import numpy as np

a : np.ndarray = np.array(10000) # object to store

print(a)
print(f"Shape: {a.shape}") # prints the shape of object () = 0 -denormalized
print(f"Dimensions: {a.ndim}") # prints the number of dimensions
print(f"Size: {a.size}") # prints the size of object
print(f"ItemSize: {a.itemsize}") # prints the itemsize of the object
print(f"Type: {a.dtype}")
print(f"{type(a)}")

10000
Shape: ()
Dimensions: 0
Size: 1
ItemSize: 4
Type: int32
<class 'numpy.ndarray'>


In [15]:
import numpy as np

x : np.ndarray = np.array((1,3,5,5)) # passing tuple

print(x)
print(f"Shape: {x.shape}") # prints the shape of object () = 0 -denormalized
print(f"Dimensions: {x.ndim}") # prints the number of dimensions
print(f"Size: {x.size}") # prints the size of object
print(f"ItemSize: {x.itemsize}") # prints the itemsize of the object
print(f"Type: {x.dtype}")
print(f"{type(x)}")

[1 3 5 5]
Shape: (4,)
Dimensions: 1
Size: 4
ItemSize: 4
Type: int32
<class 'numpy.ndarray'>


In [5]:
from typing import Any
import numpy as np
from nptyping import NDArray,Shape

x : NDArray[np.int64] = np.array([1,2,3,5])
print(x)
print(x.shape)
print(type(x))
x

[1 2 3 5]
(4,)
<class 'numpy.ndarray'>


array([1, 2, 3, 5])

## Vector Type

### 1-dimensional Numpy Array

In [14]:
from nptyping import NDArray,Shape
from typing import Any
import numpy as np
x : NDArray[Shape['5'],Any] = np.arange(1,6)
print(x.ndim)
print(x.dtype)
print(x.shape)
print(NDArray)
print(x)

1
int32
(5,)
NDArray[Any, Any]
[1 2 3 4 5]


### 2-dimensional Numpy Array

In [2]:
import numpy as np
x = np.array([[234,321,53],[2342,53,2523]])
print(x.ndim)
print(x.shape)
print(x)

2
(2, 3)
[[ 234  321   53]
 [2342   53 2523]]


### 3-dimensional NumpyArray

In [10]:
x = np.array([
    [
        [1,2],[4,5],[7,8]
    ],
    [
        [10,11],[13,14],[16,17]
    ],
    [
        [19,20],[22,23],[25,26]
    ]
    ])

print(x.ndim)
print(x)

3
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]


### Higher-order Dimensional Array

In [4]:
x = np.array([1,4,5],ndmin=5)
print(x.ndim)
print(x)

5
[[[[[1 4 5]]]]]


# Shape

In [2]:
import numpy as np
x = np.array([[234,321,53],[2342,53,2523]])
print(x)
print(x.ndim) # prints dimension of numpy array
print(x.shape) # prints shape(row,col) of numpy array

[[ 234  321   53]
 [2342   53 2523]]
2
(2, 3)


In [3]:
x = np.array([
    [
        [1,2],[4,5],[7,8]
    ],
    [
        [10,11],[13,14],[16,17]
    ],
    [
        [19,20],[22,23],[25,26]
    ]
    ])

print(x)
print(x.ndim)
print(x.shape)

[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
3
(3, 3, 2)


In [4]:
x = np.array([1,2,3,5,7], ndmin=7)
print(x)
print(x.ndim)
print(x.shape)

[[[[[[[1 2 3 5 7]]]]]]]
7
(1, 1, 1, 1, 1, 1, 5)


# Re-shape

### Changing dimensions of numpy array

In [20]:
arr = np.array([1,2,3,4,5,6])

reshape1 = arr.reshape(3,2)
print(reshape1)
print(reshape1.ndim)
print()
reshape2 = arr.reshape(6,1)
print(reshape2)
print(reshape2.ndim)
print()
reshape3 = arr.reshape(1,6)
print(reshape3)
print(reshape3.ndim)

[[1 2]
 [3 4]
 [5 6]]
2

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
2

[[1 2 3 4 5 6]]
2


In [22]:
arr = np.array([[1,2,6],[3,4,5]])
print(arr)
print(arr.ndim)
print(arr.shape)
print()
reshape1 = arr.reshape(3,2)
print(reshape1)
print(reshape1.ndim)
print()
reshape2 = arr.reshape(1,6)
print(reshape2)
print(reshape2.ndim)

[[1 2 6]
 [3 4 5]]
2
(2, 3)

[[1 2]
 [6 3]
 [4 5]]
2

[[1 2 6 3 4 5]]
2


#### Error-> If numpy array re-shaping requires more element than original array

In [19]:
arr = np.array([[1,2,6],[3,4,5]])
print(arr)

reshape = np.reshape(2,4)
print(reshape)

[[1 2 6]
 [3 4 5]]


ValueError: cannot reshape array of size 1 into shape (4,)

In [29]:
arr = np.array([1,2,6,3,4,5])
reshape = arr.reshape(3,2,1) #reshape(number_of_rows,number_of_cols,number_of_element)
print(reshape)
print(reshape.ndim)

[[[1]
  [2]]

 [[6]
  [3]]

 [[4]
  [5]]]
3


### Converting to one dimension array from any

In [36]:
arr = np.array([[[1,2],[6,3],[4,5]],[[1,2],[3,4],[8,2]]])

print(arr)
print()
print(arr.ndim)
print()

reshape = arr.reshape(-1) # convert directly to one dimension array
print(reshape)
print(reshape.ndim)

[[[1 2]
  [6 3]
  [4 5]]

 [[1 2]
  [3 4]
  [8 2]]]

3

[1 2 6 3 4 5 1 2 3 4 8 2]
1


## Boolean Slicing

In [9]:
import numpy as np
array1 = np.array([1,3,50,923,25,23,6,464,734,7,346])
boolArray = array1 % 2 == 0
print(boolArray)
print(array1[boolArray])

[False False  True False False False  True  True  True False  True]
[ 50   6 464 734 346]


In [15]:
import numpy as np

array2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ])


b_array = array2d % 2 == 0
print(b_array)
print("=============")
print(array2d[b_array])
print("=============")

arr2d = array2d.copy()
arr2d[b_array] = 0
print(arr2d)

[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]
[[1 0 3]
 [0 5 0]
 [7 0 9]]


In [19]:
# Random Integers
import numpy as np
rndm = np.random.randint(0,200,5) #(start,end,total_numbers_to_generate)
print(rndm)


[139  42   8 124 187]


#### in1d Function

In [2]:
import numpy as np

arr1 = np.arange(10)
arr2 = np.random.randint(0,10,10)

print(arr1)
print(arr2)

#in1d --> Returns a boolean array the same length as ar1 that is True
# where an element of ar1 is in ar2 and False otherwise.
arr1[np.in1d(arr1,arr2)]

[0 1 2 3 4 5 6 7 8 9]
[0 1 7 5 3 5 1 3 2 6]


array([0, 1, 2, 3, 5, 6, 7])

#### intersect1d function

In [6]:
import numpy as np

arr1 = np.arange(10)
arr2 = np.random.randint(0,10,10)

print(arr1)
print(arr2)

# intersect1d -------> Find the intersection of two arrays.
arr3 = np.intersect1d(arr1,arr2)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[6 5 4 8 7 6 6 5 4 6]
[4 5 6 7 8]


#### np.where(), np.ones(), np.zeros(), and np.ones_like().

In [9]:
import numpy as np

a = np.arange(12)

b = np.where(a>6)
print(b)

print("======================")

arr1 = np.array([1,2,5,8,10])
arr2 = np.array([2,5,9,3,7])

np.where(arr1>arr2,arr1,arr2)

(array([ 7,  8,  9, 10, 11], dtype=int64),)


array([ 2,  5,  9,  8, 10])

In [10]:
np.who()

Name            Shape            Bytes            Type

_               5                20               int32
a               12               48               int32
arr1            5                20               int32
arr2            5                20               int32
_9 (_)          5                20               int32

Upper bound on total bytes  =       108


In [14]:
import numpy as np

a = np.arange(4*3).reshape(4,3)
b = np.arange(6*3).reshape(6,3)
print(a)
print("========================")
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [25]:
import numpy as np

a = np.zeros(4) # Single Dimension
b = np.zeros((3,4)) # Two Dimension
c = np.zeros((2,4,3)) # Three Dimension
d = np.ones((3,4))
e = np.zeros_like((2,5))
f = np.ones_like((3,4))
print(a)
print("=========================")
print(b)
print("=========================")
print(c)
print("=========================")
print(d)
print("=========================")
print(e)
print("=========================")
print(f)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 0]
[1 1]


In [37]:
import numpy as np

arr = np.arange(1,21)

print(arr)
print(arr.min())
print(arr.max())
print(arr.argmin())
print(arr.argmax())
print(arr.mean()) # To find Mean of the data
print(arr.std()) # Compute the standard deviation of the function
print(arr.sum())
print(arr.cumsum()) 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
20
0
19
10.5
5.766281297335398
210
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210]
